[sssd]
domains = lab.local
config_file_version = 2
services = nss, pam

[domain/lab.local]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://localhost
ldap_search_base = dc=lab,dc=local
ldap_default_bind_dn = cn=Directory Manager
ldap_default_authtok = AdminPass123
ldap_id_use_start_tls = false
ldap_tls_reqcert = never
cache_credentials = true
enumerate = true

[nss]
default_shell = /bin/bash
homedir_substring = /home

[pam]
offline_credentials_expiration = 60
